table Room
	lineageTag: f41a9c7f-8e3e-49c4-87db-674e382e64c5

	column reserved_room_type
		dataType: string
		lineageTag: b971d2ed-9b7e-4a9d-a056-389f7e036fbd
		summarizeBy: none
		sourceColumn: reserved_room_type

		annotation SummarizationSetBy = Automatic

	column room_id
		dataType: int64
		formatString: 0
		lineageTag: 21f3f797-6631-406d-adc9-1c754b7d4981
		summarizeBy: sum
		sourceColumn: room_id

		annotation SummarizationSetBy = Automatic

	partition Room = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\T.Viswa Tejaswini\OneDrive\Documents\Desktop\viswa\hotel_booking.csv\hotel_booking.csv"),[Delimiter=",", Columns=36, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"hotel", type text}, {"is_canceled", Int64.Type}, {"lead_time", Int64.Type}, {"arrival_date_year", Int64.Type}, {"arrival_date_month", type text}, {"arrival_date_week_number", Int64.Type}, {"arrival_date_day_of_month", Int64.Type}, {"stays_in_weekend_nights", Int64.Type}, {"stays_in_week_nights", Int64.Type}, {"adults", Int64.Type}, {"children", Int64.Type}, {"babies", Int64.Type}, {"meal", type text}, {"country", type text}, {"market_segment", type text}, {"distribution_channel", type text}, {"is_repeated_guest", Int64.Type}, {"previous_cancellations", Int64.Type}, {"previous_bookings_not_canceled", Int64.Type}, {"reserved_room_type", type text}, {"assigned_room_type", type text}, {"booking_changes", Int64.Type}, {"deposit_type", type text}, {"agent", Int64.Type}, {"company", Int64.Type}, {"days_in_waiting_list", Int64.Type}, {"customer_type", type text}, {"adr", type number}, {"required_car_parking_spaces", Int64.Type}, {"total_of_special_requests", Int64.Type}, {"reservation_status", type text}, {"reservation_status_date", type date}, {"name", type text}, {"email", type text}, {"phone-number", type text}, {"credit_card", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Change Type", each true),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Filtered Rows", {{"arrival_date_year", type text}, {"arrival_date_day_of_month", type text}}, "en-IN"),{"arrival_date_year", "arrival_date_month", "arrival_date_day_of_month"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"arrival_date"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Merged Columns",{{"arrival_date", type date}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "hotel", "hotel - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"hotel - Copy", "hotel_id"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","Resort Hotel","H01",Replacer.ReplaceText,{"hotel_id"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","City Hotel","H02",Replacer.ReplaceText,{"hotel_id"}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Replaced Value1", "meal", "meal - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column1",{{"meal - Copy", "Cost"}}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns1","BB","9.99",Replacer.ReplaceText,{"Cost"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","FB","17.99",Replacer.ReplaceText,{"Cost"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","HB","13.99",Replacer.ReplaceText,{"Cost"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","SC","25",Replacer.ReplaceText,{"Cost"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Undefined","0",Replacer.ReplaceText,{"Cost"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value6",{{"Cost", type number}}),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Changed Type1", "market_segment", "market_segment - Copy"),
				    #"Renamed Columns2" = Table.RenameColumns(#"Duplicated Column2",{{"market_segment - Copy", "discount"}}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Renamed Columns2","Undefined","0",Replacer.ReplaceText,{"discount"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Direct","0.05",Replacer.ReplaceText,{"discount"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","Groups","0.08",Replacer.ReplaceText,{"discount"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","Corporate","0.12",Replacer.ReplaceText,{"discount"}),
				    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","Aviation","0.15",Replacer.ReplaceText,{"discount"}),
				    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","Offline TA/TO","0.20",Replacer.ReplaceText,{"discount"}),
				    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","Online TA","0.25",Replacer.ReplaceText,{"discount"}),
				    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","Complementary","1",Replacer.ReplaceText,{"discount"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value14",{{"discount", type number}}),
				    #"Duplicated Column3" = Table.DuplicateColumn(#"Changed Type2", "reserved_room_type", "reserved_room_type - Copy"),
				    #"Renamed Columns3" = Table.RenameColumns(#"Duplicated Column3",{{"reserved_room_type - Copy", "room_id"}}),
				    #"Replaced Value15" = Table.ReplaceValue(#"Renamed Columns3","A","1",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","C","3",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","D","4",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","E","5",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","B","2",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","F","6",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","G","7",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","H","8",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","L","9",Replacer.ReplaceText,{"room_id"}),
				    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","P","10",Replacer.ReplaceText,{"room_id"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value24",{{"room_id", Int64.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type3", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns4" = Table.RenameColumns(#"Added Index",{{"Index", "booking_id"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns4", "Date_key", each Date.Year([arrival_date]) * 10000
				+ Date.Month([arrival_date]) * 100
				+ Date.Day([arrival_date])),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom",{{"Date_key", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type4",{"reserved_room_type", "room_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"room_id"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

